// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminLogout() {
  return window['go']['main']['App']['AdminLogout']();
}

export function ConnectTunnel(arg1, arg2) {
  return window['go']['main']['App']['ConnectTunnel'](arg1, arg2);
}

export function DisconnectTunnel() {
  return window['go']['main']['App']['DisconnectTunnel']();
}

export function EnableAsExitNode(arg1, arg2) {
  return window['go']['main']['App']['EnableAsExitNode'](arg1, arg2);
}

export function ForceDisconnectTunnel() {
  return window['go']['main']['App']['ForceDisconnectTunnel']();
}

export function GetAdminConsoleURL() {
  return window['go']['main']['App']['GetAdminConsoleURL']();
}

export function GetLoggedInUser() {
  return window['go']['main']['App']['GetLoggedInUser']();
}

export function GetSessionUserJSON() {
  return window['go']['main']['App']['GetSessionUserJSON']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListDevicesJSON() {
  return window['go']['main']['App']['ListDevicesJSON']();
}

export function ListExitNodesJSON() {
  return window['go']['main']['App']['ListExitNodesJSON']();
}

export function ListSavedAccountsJSON() {
  return window['go']['main']['App']['ListSavedAccountsJSON']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function LoginWithGoogle() {
  return window['go']['main']['App']['LoginWithGoogle']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PrepareAdminSession() {
  return window['go']['main']['App']['PrepareAdminSession']();
}

export function RegisterAdminDevice(arg1, arg2) {
  return window['go']['main']['App']['RegisterAdminDevice'](arg1, arg2);
}

export function RemoveSavedAccount(arg1) {
  return window['go']['main']['App']['RemoveSavedAccount'](arg1);
}

export function RestartAsAdministrator() {
  return window['go']['main']['App']['RestartAsAdministrator']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function WakeDevice(arg1) {
  return window['go']['main']['App']['WakeDevice'](arg1);
}
