// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminAPIJSON(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AdminLogout():Promise<string>;

export function CheckForUpdateJSON():Promise<string>;

export function ConnectTunnel(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DisconnectTunnel():Promise<string>;

export function EnableAsExitNode(arg1:string,arg2:string):Promise<string>;

export function ForceDisconnectTunnel():Promise<string>;

export function GetAdminConsoleURL():Promise<string>;

export function GetAppVersionJSON():Promise<string>;

export function GetLoggedInUser():Promise<string>;

export function GetSessionUserJSON():Promise<string>;

export function GetShareAsExit():Promise<boolean>;

export function GetStatus():Promise<string>;

export function GetSystemStatus():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function ListDevicesJSON():Promise<string>;

export function ListExitNodesJSON():Promise<string>;

export function ListSavedAccountsJSON():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function LoginWithGoogle():Promise<string>;

export function Logout():Promise<string>;

export function PrepareAdminSession():Promise<string>;

export function RegisterAdminDevice(arg1:string,arg2:string):Promise<string>;

export function RemoveSavedAccount(arg1:string):Promise<string>;

export function RestartAsAdministrator():Promise<string>;

export function SetShareAsExit(arg1:boolean,arg2:string):Promise<string>;

export function SwitchAccount(arg1:string):Promise<string>;

export function VerifyExitRouteJSON():Promise<string>;

export function WakeDevice(arg1:string):Promise<string>;
