// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectTunnel(arg1) {
  return window['go']['main']['App']['ConnectTunnel'](arg1);
}

export function DisconnectTunnel() {
  return window['go']['main']['App']['DisconnectTunnel']();
}

export function GetLoggedInUser() {
  return window['go']['main']['App']['GetLoggedInUser']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}
