// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectTunnel(arg1:string,arg2:string):Promise<string>;

export function DisconnectTunnel():Promise<string>;

export function GetStatus():Promise<string>;
